# Generated by Django 2.2.12 on 2020-07-02 17:04

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def backfill_timecard_organization_and_unit(apps, schema_editor):
    """
    In hours_0055 we completed an initial backfil of existing timecards
    for this data. A bug, resolved in
    4031757630a3c74fe4d5cccc9fccc12362b77287, led to the existence
    of a few hundred timecards without organization/unit data.

    We're running the backfill again, limited to impacted timecards
    to remediate.
    """
    Timecard = apps.get_model('hours', 'Timecard')
    UserData = apps.get_model('employees', 'UserData')

    for timecard in Timecard.objects.filter(organization=None):
        try:
            user_data = UserData.objects.get(user=timecard.user)
            timecard.organization = user_data.organization
            timecard.unit = user_data.unit
            timecard.save()
        except ObjectDoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0059_auto_20200618_1041'),
    ]

    operations = [
                migrations.RunPython(backfill_timecard_organization_and_unit)
    ]
